[project]
name = "evetradeanalyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "django>=5.1.4",
    "psycopg2>=2.9.10",
]

