# Generated by Django 5.1.4 on 2024-12-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='is_buy_order',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AddIndex(
            model_name='marketorder',
            index=models.Index(fields=['item', 'price'], name='trade_analy_item_id_12c905_idx'),
        ),
    ]
