# Generated by Django 5.1.4 on 2024-12-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_analysis', '0003_profitabledeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitabledeal',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
