# Generated by Django 5.1.4 on 2024-12-26 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_analysis', '0006_alter_marketorder_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitabledeal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
